# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  create-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/setup-node@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN_DEPLOY }}
    - name: Build the image 
      run: docker build . --tag ghcr.io/pemsa-devbk/rpc-mw/rpc-mw:latest
        
        