# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deploy:
   
    runs-on: ubuntu-latest
    steps: 
      - name: install sshpass
        run: sudo apt-get install -y sshpass
      - name: SSH into server
        run: |
          sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} -p 3000 <<EOF cd dp/pemsa/back/service_9000_datamw/
          echo "Ingresó al directorio dp/pemsa/back/service_9000_datamw/"
          echo "SERVER_USER: ${{ secrets.SERVER_USER }}"
          echo "SERVER_IP: ${{ secrets.SERVER_IP }}"
          docker login ghcr.io -u pemsa-devbk -p ${{ secrets.TOKEN_DEPLOY }}
          echo "Iniciando el pull de la imagen"
          docker pull ghcr.io/pemsa-devbk/rpc-mw/rpc-mw:latest
          echo "Termino el pull de la imagen"
          echo "Deteniendo y eliminando el contenedor existente"
          docker container stop service_mw && docker container rm service_mw
          echo "Iniciando el contenedor con la nueva imagen"
          docker run -d \
            --name service_mw \
            -p 3000:9000 \
            --restart always \
            ghcr.io/pemsa-devbk/rpc-mw/rpc-mw:latest 
          EOF
